#
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /Users/zhaohao/Downloads/git project/WeChatOrderingSystem/log
#  file: /Users/zhaohao/Downloads/git project/WeChatOrderingSystem/log/sell.log
#  level:
#    com:
#      imooc:
#        service:
#          LoggerTest: debug
