#
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  path: /Users/zhaohao/Downloads/git project/WeChatOrderingSystem/log
#  file: /Users/zhaohao/Downloads/git project/WeChatOrderingSystem/log/sell.log
#  level:
#    com:
#      imooc:
#        service:
#          LoggerTest: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.26/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell

wechat:
#  openid:oTgZpwZQ6W2U2Od1iYrqN8u3evn0
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 098F6BCD4621D373CADE4E832627B4F6
  keyPath: /Users/zhaohao/Downloads/git project/WeChatOrderingSystem/path/h5.p12
